# Generated by Django 4.0.4 on 2022-05-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_sizecategory_rename_category_colorcategory_and_more'),
        ('store', '0004_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='color_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.colorcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.sizecategory'),
        ),
    ]
