# Generated by Django 4.0.4 on 2022-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_category_product_category'),
        ('category', '0002_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories/')),
            ],
            options={
                'verbose_name': 'size category',
                'verbose_name_plural': 'size categories',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ColorCategory',
        ),
        migrations.AlterModelOptions(
            name='colorcategory',
            options={'verbose_name': 'color category', 'verbose_name_plural': 'color categories'},
        ),
    ]
